- src/Title/Title.js
- src/Title/Title.stories.js
- src/Title/Title.test.js
The addition of a `<Title>` component that adheres and enforces the Typography Design Guidelines on its children text
- Add Title component and its tests and stories 
> Add Title common component

- src/index.js
Added the Title component in #20 but did not add it to list of exports 
- Add Title component to default export object and named exports. 
> Export Title common component

- README.md
> feat(add): add readme

- src/Form/FormInputs/TextAreaInput/TextAreaInput.tsx
Updating common components inputs
Added value to TextAreaInput.
> Add value to TextAreaInput

- src/types/Form/FormInputs/SelectInput/index.tsx
Updating common input type
Updated SelectInput label type to accept nodes
> Update SelectInput label type to accept nodes

- package-lock.json
- package.json
Added react testing library to get features out of the box. These features will be used in writing test cases for React components.
Installed npm package for react testing library to write unit test cases.
> [V360-8821] feat (testing): add React testing library

- package.json
- src/Alert/Alert.module.scss
- src/Alert/Alert.test.js
- src/Alert/Alert.tsx
- src/Alert/AlertHelper.test.js
- src/Alert/AlertProvider.test.js
- src/Alert/AlertProvider.tsx
- src/Alert/useManageAlerts.tsx
Wrote unit test cases for Alerts.
Wrote unit test cases for following files 
- Alert.js
- AlertProvider.js
- AlertHelper.js
> [V360-8809] feat testing : Alert test cases

- src/types/Page/index.tsx
- src/types/Panel/index.tsx
No props are required for both Page and Panel components
A brief description of the changes included in the PR. (i.e. rationale behind solution for implementation of a new feature, etc.) Before/After screenshots if applicable.
| Before | After |
| ------ | ----- |
| <before_screenshot> | <after_screenshot> |
> Fix Page and Panel types

- src/Alert/AlertProvider.test.js
- src/Button/Button.test.js
- src/Button/ButtonHelper.test.js
Wrote unit test cases for Button
Wrote unit test cases for following files
Button.tsx
ButtonHelper.tsx
> [V360-8811] feat testing :  Button test cases

- src/Loader/ReactLoader.test.js
Added test cases for Laoder component using React testing library to increase code coverage.
Added test file for ReactLoader.tsx file
> [V360-8812] feat testing : Add Loader test cases

- src/Page/Page.css
- src/Page/Page.test.js
- src/Page/Page.tsx
- src/types/Page/index.tsx
Added unit test cases for Page component to increase code coverage.
Added unit test cases for Page.tsx file
> [V360-8815] feat testing : Added test cases for Page component

- src/Form/FormInputs/SelectInput/SelectInput.tsx
- src/MultiDropdownInputWithSearch/MultiDropdownInputWithSearch.tsx
- src/MultiDropdownInputWithSearch/MultipleDropdownInputWithsearch.module.scss
- src/MultiDropdownInputWithSearch/MultipleDropdownInputWithsearch.stories.js
- src/Table/FilterPillbox/FilterHelper.js
- src/Table/FilterPillbox/FilterPillbox.module.scss
- src/Table/FilterPillbox/FilterPillbox.tsx
- src/index.js
- src/types/FilterPillbox/index.tsx
- src/types/MultiDropdownInputWithSearch/index.tsx
Add MultiDropdownInputWithSearch and filterPillbox component
- Add MultiDropdownInputWithSearch
> [Plat-6] feat(dropdown): add multiDropdownInputWithSearch

- src/Title/Title.test.js
- src/Title/Title.tsx
Added test cases for Title component
Added test case following test case file : 
- Title.test.js
> [V360-8817] feat testing : Added test cases for Title

- src/NavBar/NavBar.test.js
- src/NavBar/NavBar.tsx
- src/NavBar/NavBarHelper.test.js
- src/NavBar/ProfilePopover.test.js
- src/NavBar/ProfilePopover.tsx
Added test cases for NavBar component using React testing library
Added test case files : 
- NavBar.test.js 
- NavBarHelper.test.js
- ProfilePopover.test.js
> [V360-8814] feat testing : Added test cases for NavBar component

- src/Sidebar/Sidebar.module.scss
- src/Sidebar/Sidebar.test.js
- src/Sidebar/Sidebar.tsx
- src/Sidebar/SidebarTabs.test.js
- src/Sidebar/SidebarTabs.tsx
- src/types/Sidebar/index.tsx
Write test. cases for sidebar component
Added test case files : 
- Sidebar.test.js
- SidebarTabs.test.js
> [V360-8816] feat testing : Added test cases for sidebar

- src/Sidebar/Sidebar.tsx
- src/types/Button/index.tsx
- src/types/Sidebar/index.tsx
Fixing the sidebar error message.
Fixing the sidebar error message.
> Fix Sidebar type

- src/Tooltip/Tooltip.module.scss
- src/Tooltip/Tooltip.stories.js
- src/Tooltip/Tooltip.test.js
- src/Tooltip/Tooltip.tsx
- src/types/Tooltip/index.tsx
Added tooltip feature in common-components
A brief description of the changes included in the PR. (i.e. rationale behind solution for implementation of a new feature, etc.) Before/After screenshots if applicable.
| Before | After |
| ------ | ----- |
| <before_screenshot> | <img width="1792" alt="Screen Shot 2022-01-24 at 4 32 22 PM" src="https://user-images.githubusercontent.com/94398337/150868428-8ebdeed3-dfcb-4b71-b225-c3af812dbdba.png">
|
> [PLAT-12] feat testing : Add tooltip to common component

- src/Panel/Panel.module.scss
- src/Panel/Panel.stories.js
- src/Panel/Panel.tsx
- src/Sidebar/Sidebar.module.scss
Fixed sizing of Panel 
Fixed sizing and overflow issue in ValidereLabServices
Before : 
After :
(Changed the position of cross button of the panel to extreme right)
> [PLAT-9] feat testing : Fixed panel sizing issue

- src/AlertMessage/AlertMessage.tsx
- src/types/AlertMessage/index.tsx
Added style prop in AlertMessage to put in option for extra styling
> [PLAT-11] : feat testing : Update form alert design in common-component

- src/Modal/Modal.module.scss
- src/Modal/Modal.stories.js
Modified design of Modal component
Modified design of Modal component
> [PLAT-14] feat testing : Update modal style to match design system

- src/index.js
Exposed Alert for using it in ValidereLabServices
Updated index.js and exposed Alert so that it can used in 360.
> feat(PLAT-245): Update Alert from common-component library
